import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Inventra",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <Toaster richColors position="top-right" duration={3000} />
      {children}
    </main>
  );
}
