import { cookies } from "next/headers";
import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import AuthLayout from "./auth/layout";

export const metadata: Metadata = {
  title: "Inventra",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const defaultOpen =
    (await cookieStore).get("sidebar:state")?.value === "true";

  // Check if the current page is under the "auth" folder
  const isAuthPage =
    typeof children === "object" &&
    children !== null &&
    "props" in children &&
    children.props.childProp?.segment?.startsWith("auth");

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {isAuthPage ? (
            // Render the auth layout for pages under "auth"
            <AuthLayout>{children}</AuthLayout>
          ) : (
            // Render the full application layout
            <SidebarProvider defaultOpen={defaultOpen}>
              <AppSidebar />
              <SidebarInset>
                <Header />
                <main className="px-10">{children}</main>
              </SidebarInset>
            </SidebarProvider>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
